pipeline
{
agent any
// agent {
//   label 'DevServer'
// }

// tools {
//   maven 'mymaven'
// }

stages{

    stage('build')
    {
      steps {
          echo 'This is the build stage'
      }
        // steps {
        //     sh 'mvn clean package'
        // }

        // post {
        // success {
        //     archiveArtifacts artifacts: '**/target/*.war'
        //          }
        // }

    }

    stage('test')
    {
      steps {
        script {
          echo 'This is the test stage'
        }
      }
        // steps {
        //     sh 'mvn test'
        // }
    }

    stage('deploy')
    {
      steps {
        script {
          echo 'This is the deploy stage'
        }
      }
        // steps {
        //     sh 'mvn deploy'
        // }
    }
  }
}