pipeline
{
  agent {
    label 'server1'
  }


stages{

    stage('build')
    {
        steps {
            sh 'mvn clean package'
        }
        post {
          success {
              archiveArtifacts artifacts: '**/target/*.war'
            }
        }
    }

    stage('deploy')
    {
      steps {
        script {
          echo 'This is the deploy stage'
        }
      }
        // steps {
        //     sh 'mvn deploy'
        // }
    }
  }
}